- hosts: esx_hosts
  connection: local
  tasks:
    - name: Set Power Management Profile to Custom
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: SysProfile
        bios_attribute_value: Custom
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Set CPU Power Management to OS control
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: ProcPwrPerf
        bios_attribute_value: OsDbpm
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Set Memory Frequency to Maximum Performance
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: MemFrequency
        bios_attribute_value: MaxPerf
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Enable Turbo Boost
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: ProcTurboMode
        bios_attribute_value: Enabled
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Disable Energy Efficient Turbo
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: ControlledTurbo
        bios_attribute_value: Disabled
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Enable C1E
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: ProcC1E
        bios_attribute_value: Enabled
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Enable C States
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: ProcCStates
        bios_attribute_value: Enabled
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Set Memory Patrol Scrub to Standard
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: MemPatrolScrub
        bios_attribute_value: Standard
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Set Memory Refresh Rate to 1x
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: MemRefreshRate
        bios_attribute_value: 1x
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Set Uncore Frequency to Maximum
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: UncoreFrequency
        bios_attribute_value: MaxUFS
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Set Energy Efficient Policy to Performance
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: EnergyPerformanceBias
        bios_attribute_value: MaxPower
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Enable Mwait
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: MonitorMwait
        bios_attribute_value: Enabled
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

    - name: Disable CPU Interconnect Bus Link Power Management
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attribute_name: CpuInterconnectBusLinkPower
        bios_attribute_value: Disabled
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
      notify: "schedule BIOS setting update"

  handlers:
    - name: schedule BIOS setting update
      idrac_redfish_command:
        category: Systems
        command: CreateBiosConfigJob
        baseuri: "{{ idrac_ip }}"
        username: "{{ redfish_username }}"
        password: "{{ redfish_password }}"
